version: "3.9"
services:
  api:
    build: ./api
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs

  chat-frontend:
    build: ./chat-frontend
    env_file: .env
    ports:
      - "5173:5173"
    depends_on:
      - api

  admin-frontend:
    build: ./admin-frontend
    env_file: .env
    environment:
      - VITE_ADMIN_API_URL=http://localhost:8000
    ports:
      - "5174:5174"
    depends_on:
      - api

volumes:
  qdrant_storage:
