services:
  # Backend API
  - type: web
    name: aipl-chatbot-api
    env: python
    plan: free
    buildCommand: pip install -r api/requirements.txt
    startCommand: cd api && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: EMBEDDING_MODEL
        value: text-embedding-3-large
      - key: CHAT_MODEL
        value: gpt-4o-mini
      - key: ALLOWED_DEPARTMENTS
        value: IT,HR,Accounts,Factory,Marketing

  # Chat Frontend
  - type: static
    name: aipl-chatbot-frontend
    buildCommand: cd chat-frontend && npm install && npm run build
    staticPublishPath: chat-frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://aipl-chatbot-api.onrender.com

  # Admin Frontend
  - type: static
    name: aipl-chatbot-admin
    buildCommand: cd admin-frontend && npm install && npm run build
    staticPublishPath: admin-frontend/dist
    envVars:
      - key: VITE_ADMIN_API_URL
        value: https://aipl-chatbot-api.onrender.com
